{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.existingSecret }}
  labels:
    {{- include "go2rtc.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "credentials.username es obligatorio si credentials.create=true" .Values.credentials.username | quote }}
  password: {{ required "credentials.password es obligatorio si credentials.create=true" .Values.credentials.password | quote }}
{{- end }}
