apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.models.claimName }}
  labels:
    app.kubernetes.io/name: ra-ai-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.models.accessMode }}
  {{- with .Values.models.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.models.size }}
